import test from 'node:test';import assert from 'node:assert/strict';import {JSDOM} from 'jsdom';
import {createController} from '../src/controller.mjs';
const tick=()=>new Promise(r=>setImmediate(r));
function fixture(){
  const dom=new JSDOM('<div id="contentAreaContextMenu"></div>');const w=dom.window;w.document.createXULElement=t=>w.document.createElement(t);
  const listeners=new Set();w.gBrowser={selectedBrowser:{},tabContainer:new w.EventTarget(),addTabsProgressListener:l=>listeners.add(l),removeTabsProgressListener:l=>listeners.delete(l)};let selection='first',visible=false,destroyed=0,states=[],current=true,callbacks;const pending=[];
  const deps={selection:{capture:async()=>({rawText:selection}),isCurrent:()=>current,release(){ }},settings:()=>({englishProvider:'wiktionary-en',hebrewProvider:'wiktionary-he'}),providers:new Map([['wiktionary-en',{id:'wiktionary-en',language:'en',label:'Wiktionary'}]]),lookup:{lookup:args=>new Promise(resolve=>pending.push({args,resolve}))},createPopup:(_w,c)=>{callbacks=c;return {show(){visible=true;},render(s){states.push(s);},close(){visible=false;},destroy(){destroyed++;}};}};
  const c=createController(w,deps);return {w,c,pending,states,listeners,get callbacks(){return callbacks;},invalidate(){current=false;},setSelection:s=>selection=s,get visible(){return visible;},get destroyed(){return destroyed;},close(){c.destroy();dom.window.close();}};
}
test('rapid lookup keeps newer word even when old lookup resolves last',async t=>{const h=fixture();t.after(()=>h.close());h.c.define();await tick();h.setSelection('second');h.c.define();await tick();h.pending[1].resolve({status:'no-result'});await tick();h.pending[0].resolve({status:'ok',definition:{headword:'first'}});await tick();assert.equal(h.states.at(-1).term.query,'second');assert.equal(h.states.at(-1).outcome.status,'no-result');});
test('close and tab switch cancel late results without reopening popup',async t=>{const h=fixture();t.after(()=>h.close());h.c.define();await tick();h.w.gBrowser.tabContainer.dispatchEvent(new h.w.Event('TabSelect'));assert.equal(h.visible,false);assert(h.pending[0].args.signal.aborted);const count=h.states.length;h.pending[0].resolve({status:'no-result'});await tick();assert.equal(h.states.length,count);assert.equal(h.visible,false);});
test('replacement controller removes prior menu and owns exactly one action',t=>{const h=fixture();t.after(()=>h.close());assert.equal(h.w.document.querySelectorAll('#define-word-menu').length,1);h.c.destroy();h.c.destroy();assert.equal(h.w.document.querySelectorAll('#define-word-menu').length,0);assert.equal(h.destroyed,1);});
test('menu hidden for empty selection and password fields',t=>{const h=fixture();t.after(()=>h.close());const menu=h.w.document.getElementById('contentAreaContextMenu'),item=h.w.document.getElementById('define-word-menu');h.w.gContextMenu={isTextSelected:true,selectionInfo:{text:'secret'},onPassword:true};menu.dispatchEvent(new h.w.Event('popupshowing'));assert(item.hidden);h.w.gContextMenu={isTextSelected:true,selectionInfo:{text:'hello'},onPassword:false};menu.dispatchEvent(new h.w.Event('popupshowing'));assert(!item.hidden);});

test('menu icon is visible by default and can be disabled without removing Define',t=>{const h=fixture();t.after(()=>h.close());const item=h.w.document.getElementById('define-word-menu');assert(item.classList.contains('menuitem-iconic'));assert.equal(item.getAttribute('image'),'chrome://sine/content/define-word/assets/define-word.svg');h.c.updateAppearance({showIcon:false});assert(!item.hasAttribute('image'));assert(!item.classList.contains('menuitem-iconic'));assert(item.isConnected);h.c.updateAppearance({showIcon:true});assert(item.hasAttribute('image'));});

test('same-tab navigation cancels work and removes the progress listener on destroy',async t=>{const h=fixture();t.after(()=>h.close());h.c.define();await tick();assert.equal(h.listeners.size,1);for(const listener of h.listeners)listener.onLocationChange(h.w.gBrowser.selectedBrowser,{isTopLevel:true});assert(h.pending[0].args.signal.aborted);assert(!h.visible);const count=h.states.length;h.pending[0].resolve({status:'no-result'});await tick();assert.equal(h.states.length,count);h.c.destroy();assert.equal(h.listeners.size,0);});

test('replaced invoking frame rejects a result even before location notification and cannot be rerun',async t=>{const h=fixture();t.after(()=>h.close());h.c.define();await tick();h.invalidate();const count=h.states.length;h.pending[0].resolve({status:'no-result'});await tick();assert.equal(h.states.length,count);assert(!h.visible);h.callbacks.onProviderChange('wiktionary-en');await tick();assert.equal(h.pending.length,1);});
